# Site settings
title: iwouldnot's blog
email: iwdnot@gmail.com
description: Personal blog
url: "https://iwouldnot.me"

author:
  name     : 'Ivan Vaniushin'
  email    : iwdnot@gmail.com
  url      : https://iwouldnot.me
  vk       : https://vk.com/iwouldnot
  telegram : https://t.me/iwouldnot

disqus_shortname: "iwdnot-blog"
github: https://github.com/iwouldnot/iwouldnot.github.io

paginate: 4
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown: kramdown
  
permalink : /:title/
